services:
  - type: web
    name: bulk-mail-app
    env: node
    buildCommand: chmod +x render-build.sh && ./render-build.sh
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: BASE_URL
        value: https://your-app-name.onrender.com
      - key: RENDER
        value: true
      - fromGroup: bulk-mail-secrets # Suggested secret group
